version: "3.7"

services:
  db:
    hostname: mysql-forum
    container_name: mysql-forum
    image: mysql:8.0.19
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=forum
